services:
  cf:
    extends:
      file: docker/cf-compose.yml
      service: cf
    environment:
      aa.enabled: true
      aa.urls: "{'default': 'http://aa:8080'}"
    networks:
      - net-2-cf
  elasticsearch:
    extends:
      file: docker/cf-compose.yml
      service: elasticsearch
    networks:
      - net-2-cf
  aa:
    image: ghcr.io/archiver-appliance/epicsarchiverap:singletomcat-92c7e77
    hostname: aa
    networks:
      - net-2-cf
      - net-1-recc-1
    ports:
      - "17665:8080"
    environment:
      ARCHAPPL_APPLIANCES: /usr/local/tomcat/archappl_conf/singleappliances.xml
    volumes:
        - archapplconfig:/usr/local/tomcat/archappl_conf
        - archapplstorage:/usr/local/tomcat/storage/
  mariadb:
    hostname: mariadb
    image: mariadb
    networks:
      - net-2-cf
    environment:
      MYSQL_ROOT_PASSWORD: archappl
      MYSQL_DATABASE: archappl
      MYSQL_USER: archappl
      MYSQL_PASSWORD: archappl
    volumes:
      - archappldata:/var/lib/mysql
      - mariainit:/docker-entrypoint-initdb.d
  recc1:
    image: ghcr.io/channelfinder/recsync/recceiver:latest
    depends_on:
      cf:
        condition: service_healthy
        restart: true
    healthcheck:
      test: netstat | grep cf
      interval: 10s
      timeout: 30s
      retries: 3
    volumes:
      - type: bind
        source: docker/config/cf1.conf
        target: /home/recceiver/cf.conf
        read_only: true
      - type: bind
        source: docker/config/cf.conf
        target: /home/recceiver/channelfinderapi.conf
        read_only: true
    networks:
      - net-1-recc-1
      - net-2-cf

  ioc1-1:
    extends:
      file: ../client/ioc-compose.yml
      service: ioc1
    depends_on:
      recc1:
        condition: service_healthy
        restart: true
    environment:
      - IOCSH_NAME=IOC1-1
    hostname: ioc1-1
    networks:
      - net-1-recc-1
  ioc1-2:
    extends:
      ioc1-1
    depends_on:
      recc1:
        condition: service_healthy
        restart: true
    environment:
      - IOCSH_NAME=IOC1-2
    hostname: ioc1-1
  ioc2-1:
    extends:
      ioc1-1
    depends_on:
      recc1:
        condition: service_healthy
        restart: true
    environment:
      - IOCSH_NAME=IOC2-1
    hostname: ioc2-1
    networks:
      - net-1-recc-1
  ioc2-2:
    extends:
      ioc2-1
    depends_on:
      recc1:
        condition: service_healthy
        restart: true
    environment:
      - IOCSH_NAME=IOC2-2
    hostname: ioc2-2
networks:
  net-1-recc-1:
    driver: bridge
  net-2-cf:
    driver: bridge
volumes:

  archapplconfig:
    driver: local
    driver_opts:
      type: none
      device: ./docker/archappl/conf
      o: bind

  archapplstorage:
  archappldata:
    driver: local
  mariainit:
    driver: local
    driver_opts:
      type: none
      device: ./docker/archappl/conf/sql
      o: bind
